version: 2.1

executors:
  php-executor:
    docker:
      - image: cimg/php:8.2-node
    working_directory: ~/repo
    environment:
      MYSQL_HOST: 127.0.0.1  # Use explicit IP for MySQL
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: symfony_test

jobs:
  checkout_code:
    docker:
      - image: cimg/php:8.2-node
    steps:
      - checkout
      - run: echo "Hello, world"

  composer_install:
    docker:
      - image: cimg/php:8.2-node
    steps:
      - checkout
      - run:
          name: Install Composer Dependencies
          command: composer install --prefer-dist --no-interaction --optimize-autoloader
          
  run_tests:
    docker:
      - image: cimg/php:8.2-node
      - image: circleci/mysql:5.7  # Add MySQL if needed
    environment:
      MYSQL_ROOT_PASSWORD: root  # Needed for MySQL container
    steps:
      - checkout
      - run:
          name: Wait for MySQL to be ready
          command: |
            for i in `seq 1 30`; do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo "MySQL did not start in time" && exit 1
      - run:
          name: Create Database (if necessary)
          command: mysql -u root -proot -e 'CREATE DATABASE IF NOT EXISTS symfony_test;'
      - run:
          name: Run PHPUnit Tests
          command: ./vendor/bin/phpunit --coverage-text

  run_lint:
    docker:
      - image: cimg/php:8.2-node
    steps:
      - checkout
      - run:
          name: Run PHPLint
          command: ./vendor/bin/phplint

  run_phpstan:
    docker:
      - image: cimg/php:8.2-node
    steps:
      - checkout
      - run:
          name: Run PHPStan
          command: ./vendor/bin/phpstan analyse

  # Commented out code for OWASP ZAP scan, to be added later
  # run_zap_scan:
  #   docker:
  #     - image: owasp/zap2docker-stable:latest
  #   steps:
  #     - checkout
  #     - run:
  #         name: Start ZAP Scan
  #         command: |
  #           zap-cli start
  #           zap-cli quick-scan --self-contained http://localhost
  #           zap-cli report -o zap_report.html

  # Commented out code for syncing code to the server, to be added later
  # sync_to_server:
  #   docker:
  #     - image: cimg/php:8.2-node
  #   steps:
  #     - run:
  #         name: Sync Code to Server
  #         command: |
  #           rsync -avz --delete ./ deploy@yourserver:/var/www/yourproject
  #     - run:
  #         name: Restart Web Server
  #         command: ssh deploy@yourserver 'sudo systemctl restart apache2'

workflows:
  test_deploy:
    jobs:
      - checkout_code:
          filters:
            branches:
              only:
                - develop
                - UAT
                - master
      - composer_install:
          requires:
            - checkout_code
          filters:
            branches:
              only:
                - develop
                - UAT
                - master
      - run_tests:
          requires:
            - composer_install
          filters:
            branches:
              only:
                - develop
                - UAT
                - master
      - run_lint:
          requires:
            - run_tests
          filters:
            branches:
              only:
                - develop
                - UAT
                - master
      - run_phpstan:
          requires:
            - run_tests
          filters:
            branches:
              only:
                - develop
                - UAT
                - master
      # Uncomment these jobs when ready
      # - run_zap_scan:
      #     requires:
      #       - run_phpstan
      #     filters:
      #       branches:
      #         only:
      #           - develop
      #           - UAT
      #           - master
      # - sync_to_server:
      #     requires:
      #       - run_zap_scan
      #     filters:
      #       branches:
      #         only:
      #           - develop
      #           - UAT
      #           - master
