version: 2.1

executors:
  php-executor:
    docker:
      - image: circleci/php:7.4-node-browsers
    working_directory: ~/repo
    environment:
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: symfony_test

jobs:
  checkout_code:
    steps:
      - checkout

  composer_install:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - run:
          name: Install Composer Dependencies
          command: composer install --prefer-dist --no-interaction --optimize-autoloader
          
  run_tests:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - run:
          name: Run PHPUnit Tests
          command: vendor/bin/phpunit --coverage-text

  run_lint:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - run:
          name: Run PHPLint
          command: find . -name "*.php" -exec php -l {} \;

  run_phpstan:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - checkout
      - run:
          name: Run PHPStan
          command: vendor/bin/phpstan analyse

  run_zap_scan:
    docker:
      - image: owasp/zap2docker-stable
    steps:
      - checkout
      - run:
          name: Start ZAP Scan
          command: |
            zap-cli start
            zap-cli quick-scan --self-contained http://localhost
            zap-cli report -o zap_report.html

  sync_to_server:
    docker:
      - image: circleci/php:7.4-node-browsers
    steps:
      - run:
          name: Sync Code to Server
          command: |
            rsync -avz --delete ./ deploy@yourserver:/var/www/yourproject
      - run:
          name: Restart Web Server
          command: ssh deploy@yourserver 'sudo systemctl restart apache2'

workflows:
  version: 2
  test_deploy:
    jobs:
      - checkout_code:
          filters:
            branches:
              only:
                - develop
                - UAT
                - master
      - composer_install:
          requires:
            - checkout_code
          filters:
            branches:
              only:
                - develop
                - UAT
                - master
      - run_tests:
          requires:
            - composer_install
          filters:
            branches:
              only:
                - develop
                - UAT
                - master
      - run_lint:
          requires:
            - run_tests
          filters:
            branches:
              only:
                - develop
                - UAT
                - master
      - run_phpstan:
          requires:
            - run_tests
          filters:
            branches:
              only:
                - develop
                - UAT
                - master
      - run_zap_scan:
          requires:
            - run_phpstan
          filters:
            branches:
              only:
                - develop
                - UAT
                - master
      - sync_to_server:
          requires:
            - run_zap_scan
          filters:
            branches:
              only:
                - develop
                - UAT
                - master
