version: 2.1

executors:
  php-executor:
    docker:
      - image: cimg/php:8.2-node
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: symfony_test
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_ROOT_HOST: '%'
    working_directory: ~/repo

jobs:
  checkout_code:
    executor: php-executor
    steps:
      - checkout
      - run: echo "Hello, world"

  composer_install:
    executor: php-executor
    steps:
      - checkout
      - run:
          name: Install Composer Dependencies
          command: composer install --prefer-dist --no-interaction --optimize-autoloader

  run_tests:
    executor: php-executor
    steps:
      - checkout
      - run:
          name: Install MySQL Client
          command: sudo apt-get update && sudo apt-get install -y mysql-client
      - run:
          name: Wait for MySQL to be ready
          command: |
            for i in `seq 1 30`; do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo "MySQL did not start in time" && exit 1
      - run:
          name: Create Database (if necessary)
          command: |
            mysql -h 127.0.0.1 -u root -proot -e "CREATE DATABASE IF NOT EXISTS symfony_test;"
      - run:
          name: Run PHPUnit Tests
          command: ./vendor/bin/phpunit --coverage-text

  run_lint:
    executor: php-executor
    steps:
      - checkout
      - run:
          name: Run PHPLint
          command: ./vendor/bin/phplint

  run_phpstan:
    executor: php-executor
    steps:
      - checkout
      - run:
          name: Run PHPStan
          command: ./vendor/bin/phpstan analyse

workflows:
  test_deploy:
    jobs:
      - checkout_code
      - composer_install:
          requires:
            - checkout_code
      - run_tests:
          requires:
            - composer_install
      - run_lint:
          requires:
            - run_tests
      - run_phpstan:
          requires:
            - run_tests
